---
title: "Sea lion single locus metylation report "
output: html_notebook
author: "charles-gumbi)"
date: "2025-05-19"
---

### Loading necessary libraries
```{r}
library(dplyr)
library(stringr)
library(paletteer)
library(ggplot2)
```

### Defining the directory containing Bismark reports
```{r}
report_dir <- "~/methylation/sea_lion/bismark_output/alignment"
report_files <- list.files(report_dir, pattern = "_bismark_bt2_PE_report.txt$", full.names = TRUE)
```

### Fuction to extract the relevent infomation from ech individual file 
```{r}
# Initialize an empty list to store extracted data
report_list <- list()

# Loop through all report files and extract relevant values
for (file in report_files) {
  # Read the file as plain text
  file_content <- readLines(file)
  
  # Extract relevant alignment statistics
  TotalPairs <- as.numeric(str_extract(file_content[grep("Sequence pairs analysed in total:", file_content)], "\\d+"))
  UniqueAlignments <- as.numeric(str_extract(file_content[grep("Number of paired-end alignments with a unique best hit:", file_content)], "\\d+"))
  MappingEfficiency <- as.numeric(str_extract(file_content[grep("Mapping efficiency:", file_content)], "\\d+\\.\\d+"))
  NoAlignment <- as.numeric(str_extract(file_content[grep("Sequence pairs with no alignments under any condition:", file_content)], "\\d+"))
  NotUnique <- as.numeric(str_extract(file_content[grep("Sequence pairs did not map uniquely:", file_content)], "\\d+"))
  Discarded <- as.numeric(str_extract(file_content[grep("Sequence pairs which were discarded because genomic sequence could not be extracted:", file_content)], "\\d+"))
  TotalNumberOfCsAnalysed <- as.numeric(str_extract(file_content[grep("Total number of C's analysed", file_content)], "\\d+"))
  TotalMethylatedCsInCpGCotext <- as.numeric(str_extract(file_content[grep("Total methylated C's in CpG context:", file_content)], "\\d+"))
  TotalMethylatedCsInCHGCotext <- as.numeric(str_extract(file_content[grep("Total methylated C's in CHG context:", file_content)], "\\d+"))
  TotalMethylatedCsInCHHCotext <- as.numeric(str_extract(file_content[grep("Total methylated C's in CHH context:", file_content)], "\\d+"))
  TotalMethylatedCsInUnknownCotext <- as.numeric(str_extract(file_content[grep("Total methylated C's in Unknown context", file_content)], "\\d+"))
  TotalUnmethylatedCsInCpGCotext <- as.numeric(str_extract(file_content[grep("Total unmethylated C's in CpG context", file_content)], "\\d+"))
  TotalUnmethylatedCsInCHGCotext <- as.numeric(str_extract(file_content[grep("Total unmethylated C's in CHG context", file_content)], "\\d+"))
  TotalUnmethylatedCsInCHHCotext <- as.numeric(str_extract(file_content[grep("Total unmethylated C's in CHH context", file_content)], "\\d+"))
  TotalUnmethylatedCsInUnknownCotext <- as.numeric(str_extract(file_content[grep("Total unmethylated C's in Unknown context", file_content)], "\\d+"))
  CmethylatedInCpGcontext <- as.numeric(str_extract(file_content[grep("C methylated in CpG context", file_content)], "\\d+"))
  CmethylatedInCHGcontext <- as.numeric(str_extract(file_content[grep("C methylated in CHG context", file_content)], "\\d+"))
  CmethylatedInCHHcontext <- as.numeric(str_extract(file_content[grep("C methylated in CHH context", file_content)], "\\d+"))
  
  
  # Get sample name
  sample_name <- gsub("_bismark_bt2_PE_report.txt", "", basename(file))
  
  # Store extracted data in a list
  report_list[[sample_name]] <- data.frame(
    Sample = sample_name, 
    TotalPairs = TotalPairs, 
    UniqueAlignments = UniqueAlignments, 
    MappingEfficiency = MappingEfficiency, 
    NoAlignment = NoAlignment, 
    NotUnique = Discarded, 
    Discarded = Discarded,
    TotalNumberOfCsAnalysed=TotalNumberOfCsAnalysed,
    TotalMethylatedCsInCpGCotext=TotalMethylatedCsInCpGCotext,
    TotalMethylatedCsInCHGCotext=TotalMethylatedCsInCHGCotext,
    TotalMethylatedCsInCHHCotext=TotalMethylatedCsInCHHCotext,
    TotalMethylatedCsInUnknownCotext=TotalMethylatedCsInUnknownCotext,
    TotalUnmethylatedCsInCpGCotext=TotalUnmethylatedCsInCpGCotext,
    TotalUnmethylatedCsInCHGCotext=TotalUnmethylatedCsInCHGCotext,
    TotalUnmethylatedCsInCHHCotext=TotalUnmethylatedCsInCHHCotext,
    TotalUnmethylatedCsInUnknownCotext=TotalUnmethylatedCsInUnknownCotext,
    CmethylatedInCpGcontext=CmethylatedInCpGcontext,
    CmethylatedInCHGcontext=CmethylatedInCHGcontext,
    CmethylatedInCHHcontext=CmethylatedInCHHcontext)
}

# Combine all extracted data into a single dataframe
final_dataframe <- bind_rows(report_list)

# Save the combined dataframe as a CSV file
write.csv(final_dataframe, "~/methylation/sealion_clock/output_csv/combined_bismark_alignment_summary.csv", row.names = FALSE)
```

### Creating summary statistics
```{r}

summary_stats <- final_dataframe %>%
  summarise(
    Sample  = n(),
    Mean_Mapping_Efficiency = mean(MappingEfficiency , na.rm = TRUE),
    SD_Mapping_Efficiency = sd(MappingEfficiency , na.rm = TRUE),
    Mean_CpG_Methylation = mean(CmethylatedInCpGcontext, na.rm = TRUE),
    SD_CpG_Methylation = sd(CmethylatedInCpGcontext, na.rm = TRUE),
    Mean_Total_Reads = mean(TotalPairs , na.rm = TRUE),
    SD_Total_Reads = sd(TotalPairs , na.rm = TRUE))
# Print summary statistics
print(summary_stats)
```



### Mapping efficiency plot
```{r mapping_plot}
mapping_plot <- ggplot(final_dataframe, aes(x = Sample, y = MappingEfficiency)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title ="Mapping Efficiency Across Samples",
       y = "Mapping Efficiency (%)",
       x = "Sample") + 
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(colour="black", size=12),
        panel.border = element_rect(colour="black", fill = NA, size=1), 
        panel.background = element_blank(), 
        plot.title = element_text(hjust=0.5, size=15),
        text = element_text(size = 12,  family = "sans"))
  
mapping_plot
ggsave(plot = mapping_plot, filename = "~/methylation/sealion_clock/output_plot/mapping_plot.png" , width = 8, height = 6, dpi = 300)
```

###  Visualizing methylation levels in three context (i.e. CpG, CHH, CHG) across samples. 
```{r meltylation_level_plot}
methylation_long <- final_dataframe %>%
    pivot_longer(cols = c(CmethylatedInCHHcontext, CmethylatedInCHGcontext, CmethylatedInCpGcontext),
                 names_to = "Cytosine_context",
                 values_to = "Methylation")

methylation_plot <- ggplot(methylation_long, aes(x = Sample, y = Methylation, fill = Cytosine_context)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(title = "Methylation level", 
       y = "Methylation (%)",
       x = "Sample", 
       fill = "Cytosine context") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(colour="black", size=12),
        panel.border = element_rect(colour="black", fill = NA, size=1), 
        panel.background = element_blank(), 
        plot.title = element_text(hjust=0.5, size=15),
        text = element_text(size = 12,  family = "sans"))
methylation_plot

ggsave(plot = methylation_plot, filename = "~/methylation/sealion_clock/output_plot/methylation_plot.png", width = 8, height = 6, dpi = 300)
```


